name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      # container names must be lower case
      - name: Image Name
        id: image_name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.image_name.outputs.lowercase }}:${{ github.sha }}
            ghcr.io/${{ steps.image_name.outputs.lowercase }}:${{ github.ref_name }}
